version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cmdb-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: cmdb
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - cmdb-network

  cmdb-api:
    build: ./backend
    container_name: cmdb-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/cmdb?authSource=admin
      PORT: 8080
    depends_on:
      - mongodb
    volumes:
      - ./frontend:/app/frontend
    networks:
      - cmdb-network

volumes:
  mongodb_data:

networks:
  cmdb-network:
    driver: bridge