services:
  mongodb:
    image: mongo:7.0
    container_name: cmdb-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: cmdb
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - cmdb-network

  consul:
    image: consul:1.15
    container_name: cmdb-consul
    restart: unless-stopped
    ports:
      - "8500:8500"  # UI and API
      - "8600:8600/udp"  # DNS
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    volumes:
      - consul_data:/consul/data
    networks:
      - cmdb-network

  cmdb-api:
    build: ./backend
    container_name: cmdb-api
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      MONGO_URI: mongodb://admin:password123@mongodb:27017/cmdb?authSource=admin
      CONSUL_ADDRESS: consul:8500
      PORT: 8081
      SERVICE_ADDRESS: cmdb-api
      GOPROXY: https://goproxy.cn,direct
      GOSUMDB: sum.golang.google.cn
      GO111MODULE: on
      ZHIPU_API_KEY: 3f80d61514734e559aa6c3037fcc7bd4.WkK0ulstSY0j89CU
    depends_on:
      - mongodb
      - consul
    networks:
      - cmdb-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    container_name: cmdb-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Next.js 环境变量
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: "0.0.0.0"
      # API配置 (Next.js使用NEXT_PUBLIC_前缀)
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8082/api/v1
      NEXT_PUBLIC_AI_API_BASE_URL: http://localhost:8082/api
      NEXT_PUBLIC_API_TIMEOUT: 10000
      NEXT_PUBLIC_AI_API_TIMEOUT: 30000
      NEXT_PUBLIC_DEBUG_MODE: true
    depends_on:
      - cmdb-api
    networks:
      - cmdb-network

volumes:
  mongodb_data:
  consul_data:

networks:
  cmdb-network:
    driver: bridge
